# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    #dependnecy
    - name: Restore dependencies
      run: dotnet restore Backend/SolarWatch/SolarWatch.csproj
    #build
    - name: Build
      run: dotnet build Backend/SolarWatch/SolarWatch.csproj --no-restore
    #unit test
    - name: UnitTest
      run: dotnet test Backend/Test/Test.csproj --verbosity normal
    #integration test
    - name: IntegrationTest
      run: dotnet test Backend/SW.IntegratonTes/SW.IntegratonTes.csproj --verbosity normal
